---

codecov:
  notify:
    after_n_builds: 2  # The number of test matrix+lint jobs uploading coverage
    wait_for_ci: false

  require_ci_to_pass: false

  token: 796e466d-bf08-4b98-8d5b-0e9c442aef06  # repo-scoped

comment:
  require_changes: true

coverage:
  range: 97.87..100
  status:
    patch:
      default:
        target: 100%
        flags:
        - pytest
    project:
      lib:
        flags:
        - pytest
        paths:
        - multidict/
        target: 94.05%
      tests:
        flags:
        - pytest
        paths:
        - tests/
        target: 100%
      typing:
        flags:
        - MyPy
        target: 85%

...
