---

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: 3.7

python:
  install:
  - requirements: requirements/doc.txt

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

...
