---

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: >-
      3.12

python:
  install:
  - requirements: requirements/doc.txt

sphinx:
  builder: dirhtml
  configuration: docs/conf.py
  fail_on_warning: true

...
