"""
This type stub file was generated by cyright. 
With some minor edits...
"""
from typing import Any
from multidict import *

Cython_MultiDict: MultiDict
Cython_MultiDictProxy: MultiDictProxy
Cython_CIMultiDict: CIMultiDict
Cython_CIMultiDictProxy: CIMultiDictProxy

def multidict_create() -> MultiDict:
    ...

def cimultidict_create() -> CIMultiDict:
    ...

def multidictproxy_create(inner: object) -> MultiDictProxy:
    ...

def cimultidictproxy_create(inner: object) -> CIMultiDictProxy:
    ...

def multidict_add(md: MultiDict) -> None:
    ...

def multidict_update(md: MultiDict, data: dict[str, Any]) -> None:
    ...

def multidict_copy(md: MultiDict) -> MultiDict:
    ...

def cimultidict_update(md: CIMultiDict, data: dict[str, Any]) -> None:
    ...

def cimultidict_copy(md: CIMultiDict) -> CIMultiDict:
    ...
