stages:
- stage: test
  displayName: 'Run tests'

  jobs:
  - job:
    strategy:
      matrix:
        Py35-C-Linux:
          python.version: '3.5'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py36-C-Linux:
          python.version: '3.6'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py37-C-Linux:
          python.version: '3.7'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py38-C-Linux:
          python.version: '3.8'
          no_extensions: ''
          image: 'ubuntu-latest'
        Py35-Pure-Linux:
          python.version: '3.5'
          no_extensions: 'Y'
          image: 'ubuntu-latest'
        Py36-Pure-Linux:
          python.version: '3.6'
          no_extensions: 'Y'
          image: 'ubuntu-latest'
        Py37-Pure-Linux:
          python.version: '3.7'
          no_extensions: 'Y'
          image: 'ubuntu-latest'
        Py38-Pure-Linux:
          python.version: '3.8'
          no_extensions: 'Y'
          image: 'ubuntu-latest'
#        PyPy3-Linux:
#          python.version: 'pypy3'
#          no_extensions: 'Y'
#          image: 'ubuntu-latest'
        Py35-C-Win:
          python.version: '3.5'
          no_extensions: ''
          image: 'vs2017-win2016'
        Py36-C-Win:
          python.version: '3.6'
          no_extensions: ''
          image: 'windows-latest'
        Py37-C-Win:
          python.version: '3.7'
          no_extensions: ''
          image: 'windows-latest'
        Py38-C-Win:
          python.version: '3.8'
          no_extensions: ''
          image: 'windows-latest'
        Py35-C-Mac:
          python.version: '3.5'
          no_extensions: ''
          image: 'macos-latest'
        Py36-C-Mac:
          python.version: '3.6'
          no_extensions: ''
          image: 'macos-latest'
        Py37-C-Mac:
          python.version: '3.7'
          no_extensions: ''
          image: 'macos-latest'
        Py38-C-Mac:
          python.version: '3.8'
          no_extensions: ''
          image: 'macos-latest'
    pool:
      vmImage: '$(image)'

    timeoutInMinutes: 10

    steps:
    - checkout: self
      clean: true
      submodules: true

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
        architecture: 'x64'

    - script: |
        python -m pip install --upgrade pip setuptools wheel
      displayName: 'Update pip'

    - script: |
        python setup.py install
      displayName: 'Install itself'
      env:
        MULTIDICT_NO_EXTENSIONS: '$(no_extensions)'

    - script: |
        python -m pip install -r requirements/pytest.txt
      displayName: 'Install dependencies'

    - script: |
        python -m pip install pytest-azurepipelines
      displayName: 'Install pytest-azurepipelines'

    - script: |
        python -m pytest tests -vv
      displayName: 'pytest'

    - script: |
        python -m coverage xml
      displayName: 'Prepare coverage'

    - script: |
        python -m pip install codecov
        python -m codecov -f coverage.xml -X gcov
      displayName: 'Upload coverage reports'
      condition: ne(variables['codecov.token'], '')
      env:
        CODECOV_TOKEN: $(codecov.token)
